
var CHIT_DATA = {
	'Poison': [18, '1F480', '<i class="material-icons">electric_bolt</i>: DMG'],
	'Burn': [18, '1F525', '<i class="material-icons">electric_bolt</i>: True DMG'],
	'Chill': [18, '2744', '-ATK'],
	'Shock': [18, '26A1', '-DEF'],
	'Fortify': [18, '1F6E1', '+DEF'],
	'Empower': [18, '2694', '+ATK'],
	'Charm': [18, '1F493', ''],
	'Stealth': [8, '1F300', 'Untargetable'],
	'Stun': [8, '1F4AB', 'Skip <i class="material-icons">electric_bolt</i>/<i class="material-icons">security</i>'],
	'Summon': [8, '265F', ''],
}

var CSV_DATA = `
Name	Faction	Img	Count	Level	Cost	HP	SPD	DEF	Tactic	Deploy	Act	Defend	Defeat	Win	Flavor	\n	Image Prompt
Sky Archer	Celestial	https://i.imgur.com/qhUDdCc.jpeg	3	1	2	1	3		1VP	RNG 2 ATK 1	RNG 5 FAR ATK 2			1VP		\n	generate a TCG fantasy styled semi-realistic 2d game art of a sky archer, she has angel wings with blonde hair
Sky Knight	Celestial	https://ideogram.ai/assets/image/lossless/response/IVCWZ6X2QTS8onah8zjxRg	3	1	2	3	3	2	1VP	Melee ATK 1	Melee ATK 3	Reflect ATK 1 per AOE R Celestial ally against Melee attack		1VP		\n	A semi-realistic TCG fantasy style painting art of a knight with angel wings flying in the sky. The knight is clad in gold and holds a sword and shield. The background contains clouds and a distant castle.
Martyr	Celestial	https://i.imgur.com/HOFtWOi.jpeg	3	1	1	2	3		1VP	AOE 1 Heal 1	RNG 2 Heal 2	IMM Charm	3VP	1VP		\n	A semi-realistic TCG fantasy painted style art of a medieval martyr dressed in a robe. The martyr is standing on a stone platform. Surrounding the martyr are citizens with different expressions, some of them are kneeling. The background contains a castle and trees.
Torchlighter	Celestial	https://ideogram.ai/assets/image/lossless/response/awirCrGaTfCTKKee4ZMQkQ	3	1	1	3	3		AOE R Reveal		RNG 2 ATK 1 Burn			1VP		\n	A semi-realistic TCG fantasy style art with a slight painting feel of an angel with wings holding a flaming torch in the sky. The angel is dressed in white robes and is floating in the air above a city with tall buildings. The background is cloudy with a pink and orange hue.
Imp	Chaos	https://ideogram.ai/assets/image/lossless/response/PQp5IP6TQRSBLL5B1aGM7w	3	1	2	2	4		Steal 1G from opponent	Melee ATK 1	Melee ATK 2		Melee ATK 2	1VP		\n	A semi-realistic TCG fantasy style painting art of an red Imp holding a spear, he has wings and a demon tail, flying in the sky, background is also red themed with some spiky mountains, he is smirking.
Specter	Chaos	https://ideogram.ai/assets/image/lossless/response/449eFQcYT9yBRWXrM2JtRw	3	1	2	1	3	3	Fog of war for next deployed ally	Fog of War on self	Melee ATK 3	IMM poison; DEF 1 per AOE R Chaos ally		1VP		\n	A semi-realistic TCG fantasy style painting art of a purple Specter or ghostly spirit wandering around in a dark green themed graveyard, the Specter has long hair and grueling expression
Zombie	Chaos	https://ideogram.ai/assets/image/lossless/response/f_b-RzPBT4usZl96PKbFyg	3	1	2	3	1		Melee Poison		Melee ATK 2 poison	IMM poison	AOE 1 Poison	1VP		\n	A semi-realistic TCG fantasy style painting art of a greenish Zombie wandering around a haunted graveyard
Bat	Chaos	https://i.imgur.com/HM1OVqE.jpeg	3	1	1	1	4		Draw 1 card; May Discard 1 card to draw another	Free self	RNG 2 ATK 1	IMM poison				\n	generate a TCG fantasy styled semi-realistic 2d game art of a bat flying in the woods
Ticking Bomb	Construct	https://i.imgur.com/RFSVxsJ.jpeg	3	1	1	3	3	2	Melee ATK 2	AOE 1 Burn, Self Burn			Melee ATK 8	2G		\n	
Ice Totem	Construct	https://ideogram.ai/assets/image/lossless/response/3TIsxpi3ShOLtH2w0_Axjw	3	1	1	4	2	2	Persistent end of allies' Act: remove 1 chill		Melee AOE R Chill	IMM chill; Melee AOE R Chill		1VP		\n	A semi-realistic TCG fantasy style art with a slight painting feel. There's a Mayans inspired totem with a blue theme, emitting an ice wave and chilling mist. The background is a dark, misty forest with tall trees. The overall image has a blue and white color scheme.
Mimic	Construct	https://ideogram.ai/assets/image/lossless/response/QDy14ZdxQNya3G6i-beRxA	3	1	2	4	1		1G per deployed Construct ally		AOE 1 Heal 1	Once: Nullify attack, reflect ATK 5 with ADV against melee attack	Foe gain 2G	1VP 2G		\n	
War Wagon	Construct	https://i.imgur.com/3NE1FEy.jpeg	3	1	1	3	3	2	Free 1 -2G	Free self; RNG 1 Empower		IMM Stun	Spawn a human with 1 HP			\n	Generate a TCG fantasy styled semi-realistic 2d game art of a a war wagon rushing into battle
Druid	Nature	https://i.imgur.com/BeQl6YX.jpeg	3	1	2	3	3		AOE R Heal 1, Draw 1 card	RNG 2 Cleanse 1	RNG 1 AOE R Empower 1	IMM Poison		1VP		\n	
Dire Wolf	Nature	https://i.imgur.com/WNLhG6B.jpeg	3	1	1	3	4	1	Melee AOE C ATK 1	AOE 1 Empower	Melee ATK 3			1VP		\n	
Insect Swarm	Nature	https://i.imgur.com/8QNp2rV.jpeg	3	1	1	2	3	1	Melee AOE R Poison	Free self	Melee ATK 1					\n	
Toxic Shroom	Nature	https://i.imgur.com/UauXEJD.jpeg	3	1	1	1	1		RNG 2 Poison 2		AOE 1 Heal 1 Nature allies	IMM Poison; Reflect Poison against Melee attack	AOE 2 Poison	1VP		\n	Generate a TCG fantasy styled semi-realistic 2d game art of a big toxic mushroom in the forest, the mushroom is greenish color and emits poison
Warrior	Order	https://i.imgur.com/XF9XZ4H.jpeg	3	1	1	3	3	2	Melee ATK 2		Melee ATK 3	DEF 1 per AOE R Order ally		1VP		\n	A semi-realistic TCG fantasy style art of a basic warrior in armor with a helmet, holding a sword and posing. The warrior is standing on a rocky terrain. The background reveals a castle and a bridge.
Cleric	Order	https://i.imgur.com/9GX9F0O.jpeg	3	1	2	3	2		Cleanse 2 Heal 3	1G	RNG 3 cleanse 1 heal 2			1VP		\n	Generate a TCG fantasy styled semi-realistic 2d game art of a cleric in the church blessing others, he is dressed in gold robes
Merchant	Order	https://i.imgur.com/r9rpr6n.jpeg	3	1	2	1	1		1G, Draw 1 card		1G		-1G			\n	A semi-realistic TCG fantasy style art of a merchant holding some gold coins
Apprentice	Order	https://i.imgur.com/AsYsSGZ.jpeg	3	1	2	2	3		RNG 2 Chill Shock	RNG 3 Burn	RNG 5 ATK 3			1VP		\n	Generate a TCG fantasy styled semi-realistic 2d game art of an apprentice mage, a boy casting magic holding a book
Flag Bearer	Celestial	https://i.imgur.com/t1r0nU8.jpeg	2	2	4	4	4	1	Free 1 -1G	AOE 2 Heal 1	AOE 1 Heal 1 Empower 1; Heal 1 self	Fortify self if AOE 3 >3 Celestial allies	Chill AOE 1 allies	2VP		\n	Generate a TCG fantasy styled semi-realistic 2d game art of angel flying in the sky with angel wings, holding a big flag for raising morales, he is dressed in white and gold robes
Fortune Bringer	Celestial	https://i.imgur.com/5n4PrDR.jpeg	2	2	4	3	3	3	1VP per deployed Celestial ally	Draw 2 cards	1G	IMM Poison Burn	All players get 1G (incl. self)	1G per alive ally		\n	Generate a TCG fantasy styled semi-realistic 2d game art of an angel bringing in gold, he is cloaked in gold and white color and named Fortune Bringer. full body
Valkyrie	Celestial	https://i.imgur.com/aDBsfYz.jpeg	2	2	3	4	4	2	1VP, RNG 3 ATK 3		Melee AOE C ATK 2	IMM Charm; Self Heal 1		2VP 1G		\n	A semi-realistic TCG fantasy style high-quality 2D game art with a slight painting feel. An angel is flying in the sky with angel wings. She is holding a long spear and wearing light golden armor. The angel has long golden hair. The background reveals a vast landscape with mountains, forests, and a city. The sky is clear with a few clouds.
Plague Doctor	Chaos	https://ideogram.ai/assets/image/lossless/response/PDD_DhonQ3Wh3uJPHvii6g	2	2	3	3	3	2	RNG 3 AOE 1 Poison	RNG 3 Poison	RNG 2 AOE 1 Poison	Once perform Act; IMM Poison	Heal 3 AOE 1 Chaos allies	2VP 1G		\n	A semi-realistic TCG fantasy style art of a plague doctor wearing a crow mask, holding and carrying around a bag of flasks of green potions. The background contains green smoke. The color theme is black and dark green.
Ice Demon	Chaos	https://i.imgur.com/gx2l4Th.jpeg	2	2	3	3	4	2	RNG 2 AOE R Chill	RNG 2 Chill	RNG 2 ATK 1 Chill	IMM chill		2VP 1G		\n	Generate a TCG fantasy styled semi-realistic 2d game art of an ice demon in blue color with demon wings and horns. He is holding a staff circled with icy blue energy. He is in an ice cave with ice backgrounds.
Cultist	Chaos	https://i.imgur.com/xL2F3N2.jpeg	2	2	4	4	3	2	RNG 2 Charm; Draw 1 card	Melee 1 True Damage	Melee ATK 2 Charm		AOE 2 Empower Chaos allies	1VP 1G		\n	Generate a TCG fantasy styled semi-realistic 2d game art of a cultist wearing purple cloak and robes, hood over head and face is unseen, he is performing rituals in a dark chamber, he is red and purple themed, full body.
Stone Golem	Construct	https://ideogram.ai/assets/image/lossless/response/4OADZ8wUQqm1m0qkMR8UuQ	2	2	3	5	2	4	Fortify Vanguard allies 	Melee Stun	Melee ATK 2, if dealt damage: Stun	IMM stun	Spawn a boulder with 5 HP	2VP 1G		\n	A semi-realistic TCG fantasy style 2D game art of a Stone Golem in a green forest. The Stone Golem has moss grown on it and is surrounded by small forest creatures such as squirrels and rabbits. The background reveals a dense forest with tall trees.
Magma Core 	Construct	https://ideogram.ai/assets/image/lossless/response/ybcLxQp7QGSNalcul9LuZQ	2	2	3	5	3	2	Persistent end of allies' Act: remove 1 burn	Melee AOE R Burn	Melee ATK 3 Burn	IMM burn; Reflect Burn against Melee attack	Heal 3 AOE 1 Construct allies	2VP 1G		\n	Generate a TCG fantasy styled semi-realistic 2d game art of a Magma Golem with lava flowing from its seams, standing in front of a volcano with smoke billowing from its peak. The Magma Golem has a rocky texture and is made of magma. The background is dark, with the volcano's rocky terrain and the sky filled with smoke.
Ballista	Construct	https://i.imgur.com/WBxLKdd.jpeg	2	2	4	5	2	2	RNG 3 AOE C ATK 2	Empower AOE 1 Construct allies	RNG 2 AOE C ATK 3	IMM Stun		2VP 1G		\n	Generate a TCG fantasy styled semi-realistic 2d game art of a big medieval ballista firing an arrow through the battlefield, it looks like a big archery bow mounted on platform. No sphere on it, it is not a cannon, align the arrow with the firing position of the ballista
Pixies	Nature	https://i.imgur.com/vfkLQZU.jpeg	2	2	3	3	3		Persistent on deploying Nature allies: Draw 1 card	Empower AOE 2	RNG 3 ATK X (X = current HP)	Takes 1 damage at most per attack		1G per current HP		\n	Generate a TCG fantasy styled semi-realistic 2d game art of three pixies flying in the forest
Elven Sniper	Nature	https://i.imgur.com/NwAsbTj.jpeg	2	2	3	2	2		RNG 3 ATK 3 with ADV	RNG 3 Reveal	RNG 7 ATK 4, ADV if Nature allly in AOE 1	IMM Poison		2VP 1G		\n	
Beast	Nature	https://i.imgur.com/SQNq8qt.jpeg	2	2	3	4	4	2	Melee AOE C ATK 2 with ADV	Melee AOE 1 ATK 3	Melee ATK 5	IMM Poison		2VP 1G		\n	Generate a TCG fantasy styled semi-realistic 2d game art of a beast ravaging in the woods
Thornguard	Order	https://i.imgur.com/YipsqOj.jpeg	2	2	3	5	1	5	Persistent Once: when ally is attacked: Nullify, if Order ally: Fortify		Melee ATK 3	Reflect ATK 2 against Melee attack		2VP 1G		\n	A semi-realistic TCG fantasy style high-quality 2D game art: a blue bulky knight with a tower shield and a spear, the tower shield has spikes coming out of it, the knight is blue themed, standing in front of a castle gate.
Assassin	Order	https://i.imgur.com/SAkhKlo.jpeg	2	2	3	2	5		RNG 3 Reveal and ATK 3	Stealth	RNG 5 FAR ATK 4	DEF 1 per AOE 1 Order ally		2VP 1G		\n	A realistic painted TCG fantasy style high-quality 2D game art: an assassin holding 2 daggers, he is  on top of a building, cloaked in black, in the night
Inquisitor	Order	https://i.imgur.com/iGvoGHY.jpeg	2	2	3	4	3	3	Melee AOE R ATK 2, ADV against Chaos	Chill all Chaos foes	Melee ATK 4, +2 true damage against Chaos	IMM Charm		2VP 1G		\n	Generate a TCG fantasy styled semi-realistic 2d game art of an inquisitor, he wields a morning star, he dresses black coat, he is blue and black themed, he is wearing a tophat and covered face.
Archangel	Celestial	https://ideogram.ai/assets/image/lossless/response/jGliyPujQ3qmIo4O-57Ysw	1	3	6	5	5	4	Free 2 2VP	1VP, Draw 1 card	1VP, RNG 2 Reveal ATK 3	IMM shock chill stun burn charm	Once AOE 2 revive Celestial allies up to 2 HP	3VP 3G	A symbol of hope and redemption, sent to guide humanity.	\n	A semi-realistic TCG fantasy style painting art of an archangel in full suit of armor and a shield and a sword, standing on a cloud in heaven. The archangel is wearing a white hoodie and his face cannot be seen. The archangel has wings spread wide.
Lightbringer	Celestial	https://i.imgur.com/EBSqrwd.jpeg	1	3	6	5	3	3	Persistent Reveal, 2VP	RNG 2 AOE 1 Reveal; RNG 2 ATK 3 Stun	RNG 3 ATK 3 Burn 2; Self Cleanse 1	IMM stun burn charm; DEF 1 per AOE R Celestial ally		3VP 2G	A radiant being, bathed in the light of the divine.	\n	generate a TCG fantasy styled semi-realistic 2d game art of an angel with shining halo behind her head, she is flying in the sky with eyes covered by white cloth, she has golden hair and dressed in gold and white robes, she is in an elegant stature with great posture floating in the heavens above clouds, show full body, she is bare feet
Executioner	Celestial	https://i.imgur.com/aRzximJ.jpeg	1	3	6	6	3	4	RNG 2 4 true dmg, +1 true damage per deployed Celestial ally	Melee AOE R chill	Melee ATK 6, +1 ATK per chill on target, on killing blow: 2VP			3VP 2G	The instrument of divine retribution, forced to carry out the will of the law.	\n	generate a TCG fantasy styled semi-realistic 2d game art of an executioner dressed in black and golden armor, he is wearing a hoodie where his face is not visible, he is holding a large axe and emits chilling aura, he also has angel wings, background is in on a platform
Mist Lord	Chaos	https://i.imgur.com/Vl8CuHQ.jpeg	1	3	6	6	4	3	Persistent Fog of War on all Chaos allies	Fog of War on self & AOE R allies, Stealth 2	Melee ATK 4 poison, if Stealth: ADV	IMM stun chill shock	AOE 2 Poison	3VP 2G	A phantom of the fog, a specter of the unknown.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a demon named Mist Lord. He is a wraith or specter with purple mist emanating from and around his body. He is holding a big scythe. The background is a haunting graveyard with a dark greenish color theme.
Succubus	Chaos	https://i.imgur.com/J1jwVty.jpeg	1	3	6	4	4	2	RNG 3 Charm 4	RNG 3 AOE 2 Charm	RNG 3 FAR Charm 2	Charm against attack; DEF 1 per AOE 1 Chaos ally	Remove all Charm tokens on battlefield	2VP 4G	A seductive temptress, whose beauty is a deadly illusion.	\n	generate a TCG fantasy styled semi-realistic 2d game art of sccubus with white long wavy hair, cute face, blue eyes, pale skin, demon wings and tail, blowing a kiss with one hand towards the camera, theme is red, black and purple, background is dark castle, she has diamond earrings and a spiky black crown embedded with diamonds. Art shows full body with feet
Dracula	Chaos	https://i.imgur.com/xpQCLtL.jpeg	1	3	6	5	5	4	Persistent War Phase start: RNG 3 AOE 3 ATK X (X = # deployed Chaos allies)	Fog of war on self, Stealth	Melee ATK 5, heal self for damage dealt	IMM poison	Spawn a Bat with 2/5 HP & 1 SPD, self Heal 1 on Act, at 5 HP, Dracula revives	3VP 2G	A vampire lord, whose reign of terror spans generations.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of Vampire noble, he has red and black capes, elegant look, holding a red wine glass, white hair, red eyes, background is gothic castle with bats flying around, show full body
Automaton	Construct	https://i.imgur.com/uDzkjVb.jpeg	1	3	6	7	3	5	Persistent before ally Construct act, grant them Empower	-1G	RNG 2 ATK 3 burn poison chill shock	IMM Stun Poison		3VP 2G	A mechanical marvel, capable of both wonder and destruction.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a mechanical construct in the shape of a sphere with 6 legs, it has turrets and laser beams on it shooting out of it, it is crawling through rubbles
Trebuchet	Construct	https://i.imgur.com/26DxGQE.jpeg	1	3	6	7	2	4	Persistent grant all allies +1 RNG	2VP -1G	RNG 6 ANY AOE 1 ATK 2, +1 ATK per Construct ally in AOE 1	IMM Stun Poison		3VP 2G	A harbinger of doom, raining destruction from above.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a trebuchet throwing out big boulders
Marionette	Construct	https://i.imgur.com/OiqdG7c.jpeg	1	3	6	4	3	5	Draw 1 card, +1 per deployed Construct ally	Melee ATK 3, -1G	Melee AOE R ATK 3, if killing blow: Act	IMM Stun Poison	Once self revive with full HP when ally Construct is defeated	3VP 2G	Even the greatest among us are subject to the will of others.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a marionette holding swords and spears and different weaponry
Phoenix	Nature	https://ideogram.ai/assets/image/lossless/response/IPego5E9SrSwwftZJaFGHA	1	3	6	5	4	3	RNG 2 AOE 2 Burn, 1 true DMG	2VP, 2G, RNG 2 Burn 2	RNG 2 AOE 1 ATK 3 burn	IMM Burn Shock Poison	Once revive with full HP, AOE 2 Heal 2 Nature allies 	3VP 2G	Flame that never dies, a spirit that cannot be extinguished.	\n	Painted TCG fantasy style high-quality 2D game art: a phoenix spreading its wings, shrouded in flames, looking epic
Yggdrasil	Nature	https://i.imgur.com/9JY6cgv.jpeg	1	3	6	6	1	4	Persistent Nullify killing blow Once per ally unit	AOE 2 Stun L1 & L2 foes	AOE 2 Empower, if Nature ally: Heal 1	IMM Stun; Once: Nullify killing blow	AOE 2 Empower Heal 1	3VP 2G	From its sap, life flows. From its leaves, wisdom grows.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of Yggdrasil the world tree, surround by pixies
Kraken	Nature	https://i.imgur.com/zK040u3.jpeg	1	3	6	7	2		ATK 5 to all deployed Construct enemies	Persistent end of Nature allies' Act: remove 1 chill	Melee AOE R ATK 3 Chill, if dealt damage: Stun	Takes 2 damage at most per attack		3VP 2G	Creature of darkness, guarding the secrets of the abyss.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a kraken wrecking a ship
Holy Paladin	Order	https://ideogram.ai/assets/image/lossless/response/7JaHFw7vSl-hy7zEEwMP9g	1	3	6	7	3	4	Persistent end of Vanguard or Order allies' Act: Heal 1 them; Free 1	2VP, AOE 2 Cleanse 1 Order allies	AOE 2 Cleanse 1 Heal 3, Melee ATK 3	IMM stun	AOE 1 Fortify Order allies	4VP 2G	A champion of the light, wielding the power of the divine.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a Holy Paladin is bathed in a golden light ray. The Paladin is clad in fancy glimmering armor and holds a holy sword and shield. The background contains a castle and a bridge over a body of water. The overall image has a gold theme.
War Master	Order	https://i.imgur.com/QOdfNhz.jpeg	1	3	6	5	3	4	Draw 2 cards; Trigger a deployed ally's Tactic via self	AOE 2 Cleanse 1 Empower	RNG 1 Empower Order ally, Trigger a deployed ally's Act via them	AOE 1 use any Order ally's Defend via self		3VP 2G	The greatest battles are won before they are fought.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a master tactician, he is in a tent directing on a map of the battlefield, he is clad in armor and wearing lenses
Grand Sorcerer	Order	https://i.imgur.com/1EjO5Tf.jpeg	1	3	6	4	2	3	Transfer debuffs on all allies to foes in mirror location	RNG 3 AOE 2 shock; Empower all Order allies	RNG 3 AOE 1 ATK 2 burn chill	Once nullify attack	AOE 2 Empower 2	3VP 2G	Dance with the elements, bend them to his will.	\n	Generate a TCG fantasy styled semi-realistic 2d game art of a grand sorcerer casting big circles of magic, floating mid air, surrounded by fire, ice, earth
`